import 'dart:io';
import 'package:path_provider/path_provider.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:share_plus/share_plus.dart';
import 'package:woloo_smart_hygiene/janitorial_services/screens/pdf/dummy/dummy_report_data.dart';
import 'package:woloo_smart_hygiene/janitorial_services/model/iotdata_model.dart';
import 'package:woloo_smart_hygiene/janitorial_services/model/get_task_dashboard_data.dart';
import 'package:woloo_smart_hygiene/client_flow/screens/dashbaord/data/model/dashboard_task_model.dart'
    as dashboard_task_model;

class DashboardPdfBuilder {
  static Future<void> generateAndShare({
    DashboardData? dashboardData,
    dashboard_task_model.TaskStatusDistribution? taskStatusDistribution,
    List<TaskMonitoring>? taskMonitoring,
    String? facilityName,
    String? selectedRange,
  }) async {
    /// Step 1: Get dummy data (for sections not yet mapped)
    final reportData = DummyReportData.sample();

    /// Extract KPI values from API data
    final tasksCompleted =
        DashboardPdfBuilder._getTasksCompleted(taskStatusDistribution);
    final alertsReceived =
        DashboardPdfBuilder._getAlertsReceived(dashboardData);
    final avgAqi = DashboardPdfBuilder._getAvgAqiValue(dashboardData);
    final avgUsage = DashboardPdfBuilder._getAvgUsageValue(dashboardData);
    final changesFromYesterdayAlertTrend =
        DashboardPdfBuilder._getChangesFromYesterdayAlertTrend(dashboardData);
    final changesFromAqi =
        DashboardPdfBuilder._getChangesFromAqi(dashboardData);
    final changesFromUsage =
        DashboardPdfBuilder._getChangesFromUsage(dashboardData);

    /// Step 2: Create PDF document
    final pdf = pw.Document();

    /// Step 3: Add page
    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(32),
        build: (context) {
          final data = reportData;

          return [
            /// HEADER
            pw.Center(
              child: pw.Text(
                "Facility Management Report",
                style: pw.TextStyle(
                  fontSize: 26,
                  fontWeight: pw.FontWeight.bold,
                ),
              ),
            ),

            pw.SizedBox(height: 10),

            pw.Center(
              child: pw.Text(
                facilityName ?? data.facilityName,
                style: pw.TextStyle(fontSize: 18),
              ),
            ),

            pw.SizedBox(height: 5),

            pw.Center(
              child: pw.Text(
                "Generated by: ${data.generatedBy}",
                style: const pw.TextStyle(fontSize: 12),
              ),
            ),

            pw.Center(
              child: pw.Text(
                "Date: ${data.generatedAt}",
                style: const pw.TextStyle(fontSize: 12),
              ),
            ),

            pw.Divider(height: 30),

            /// EXECUTIVE SUMMARY
            _buildSectionTitle("Executive Summary"),

            pw.Text(
              data.executiveSummary,
              style: const pw.TextStyle(fontSize: 12),
            ),

            pw.SizedBox(height: 20),

            /// KPI TABLE
            _buildSectionTitle("Key Performance Indicators"),

            pw.Table(
              border: pw.TableBorder.all(),
              children: [
                /// Header row
                pw.TableRow(
                  decoration: const pw.BoxDecoration(color: PdfColors.grey300),
                  children: [
                    _buildTableCell("Metric", isHeader: true),
                    _buildTableCell("Value", isHeader: true),
                  ],
                ),

                _buildKpiRowColored(
                  "Tasks Completed",
                  tasksCompleted,
                  PdfChartColors.blackText,
                ),

                // _buildKpiRowColored(
                //   "Changes from Yesterday",
                //   "${data.kpi.tasksCompleted}",
                //   PdfChartColors.good,
                // ),

                _buildKpiRowColored(
                  "Alerts Received",
                  alertsReceived,
                  PdfChartColors.blackText,
                ),

                _buildKpiRowColored(
                  _getChangesLabel(selectedRange),
                  changesFromYesterdayAlertTrend['value'] as String,
                  changesFromYesterdayAlertTrend['color'] as PdfColor,
                ),

                _buildKpiRowColored(
                  "Average Air Quality Index(AQI)",
                  avgAqi['value'] as String,
                  avgAqi['color'] as PdfColor,
                ),

                _buildKpiRowColored(
                  _getChangesLabel(selectedRange),
                  changesFromAqi['value'] as String,
                  changesFromAqi['color'] as PdfColor,
                ),

                _buildKpiRowColored(
                  "Total Usage",
                  avgUsage['value'] as String,
                  avgUsage['color'] as PdfColor,
                ),

                _buildKpiRowColored(
                  _getChangesLabel(selectedRange),
                  changesFromUsage['value'] as String,
                  changesFromUsage['color'] as PdfColor,
                ),
              ],
            ),

            pw.SizedBox(height: 20),

            /// ODOR LEVEL TABLE
            _buildSectionTitle("Odor Level Analysis"),
            pw.Text(
                'Odor levels are tracked throughout the day in parts per billion (ppb), correlated with facility usage patterns'),
            pw.SizedBox(height: 20),
            pw.Table(
              border: pw.TableBorder.all(),
              children: [
                pw.TableRow(
                  decoration: const pw.BoxDecoration(color: PdfColors.grey300),
                  children: [
                    _buildTableCell("Time Period", isHeader: true),
                    _buildTableCell("Odor Level", isHeader: true),
                    _buildTableCell("Usage", isHeader: true),
                    _buildTableCell("Status", isHeader: true),
                  ],
                ),
                ...DashboardPdfBuilder._buildOdorLevelRows(dashboardData),
              ],
            ),

            pw.SizedBox(height: 20),

            /// TASK AUDIT TABLE
            _buildSectionTitle("Task Audit"),

            pw.Table(
              border: pw.TableBorder.all(),
              children: [
                pw.TableRow(
                  decoration: const pw.BoxDecoration(color: PdfColors.grey300),
                  children: [
                    _buildTableCell("Task", isHeader: true),
                    _buildTableCell("Assigned To", isHeader: true),
                    _buildTableCell("Status", isHeader: true),
                  ],
                ),
                ...DashboardPdfBuilder._buildTaskAuditRows(taskMonitoring),
              ],
            ),

            pw.SizedBox(height: 20),

            /// ALERTS TABLE
            _buildSectionTitle("Critical Alerts"),
            pw.Text('The following alerts require immediate attention.'),
            pw.SizedBox(height: 20),

            pw.Table(
              border: pw.TableBorder.all(),
              children: [
                pw.TableRow(
                  decoration: const pw.BoxDecoration(color: PdfColors.grey300),
                  children: [
                    _buildTableCell("Description", isHeader: true),
                    _buildTableCell("Time", isHeader: true),
                  ],
                ),
                ...DashboardPdfBuilder._buildCriticalAlertsRows(dashboardData),
              ],
            ),

            pw.SizedBox(height: 20),

            /// JANITOR PERFORMANCE
            _buildSectionTitle("Janitor Performance"),

            pw.Table(
              border: pw.TableBorder.all(),
              children: [
                pw.TableRow(
                  decoration: const pw.BoxDecoration(color: PdfColors.grey300),
                  children: [
                    _buildTableCell("Name", isHeader: true),
                    _buildTableCell("Tasks Completed", isHeader: true),
                    _buildTableCell("Completion Rate", isHeader: true),
                  ],
                ),
                ...DashboardPdfBuilder._buildJanitorPerformanceRows(
                    taskMonitoring),
              ],
            ),

            pw.SizedBox(height: 20),

            // /// RECOMMENDATIONS
            // _buildSectionTitle("Recommendations"),

            // ...data.recommendations.map(
            //   (e) => pw.Bullet(text: e),
            // ),
          ];
        },
      ),
    );

    /// Step 4: Save PDF to temp directory
    final directory = await getTemporaryDirectory();

    final file = File(
      "${directory.path}/facility_report_${DateTime.now().millisecondsSinceEpoch}.pdf",
    );

    await file.writeAsBytes(await pdf.save());

    /// Step 5: Open Share dialog
    await Share.shareXFiles(
      [XFile(file.path)],
      text: "Facility Management Report",
    );
  }

  static pw.Widget _buildSectionTitle(String title) {
    return pw.Container(
      width: double.infinity,
      //padding: const pw.EdgeInsets.all(8),
      // color: PdfChartColors.headerBackground,
      child: pw.Text(
        title,
        style: pw.TextStyle(
          fontSize: 18,
          fontWeight: pw.FontWeight.bold,
        ),
      ),
    );
  }

  static pw.Widget _buildTableCell(
    String text, {
    bool isHeader = false,
    PdfColor? textColor,
  }) {
    return pw.Padding(
      padding: const pw.EdgeInsets.all(8),
      child: pw.Text(
        text,
        style: pw.TextStyle(
            fontSize: 12,
            fontWeight: isHeader ? pw.FontWeight.bold : pw.FontWeight.normal,
            color: textColor),
      ),
    );
  }

  static pw.Widget _buildTableCellWithBackground(
    String text, {
    PdfColor? backgroundColor,
    PdfColor? textColor,
  }) {
    return pw.Container(
      padding: const pw.EdgeInsets.all(8),
      decoration: backgroundColor != null
          ? pw.BoxDecoration(color: backgroundColor)
          : null,
      child: pw.Text(
        text,
        style: pw.TextStyle(
          fontSize: 12,
          fontWeight: pw.FontWeight.normal,
          color: textColor ?? PdfColors.black,
        ),
      ),
    );
  }

  /// Get color for completion rate based on percentage ranges
  static Map<String, PdfColor> _getCompletionRateColor(double percentage) {
    if (percentage < 30) {
      // 0-30%: Red background, white text
      return {
        'bgColor': PdfColor.fromHex("#E1272E"),
        'textColor': PdfColors.white,
      };
    } else if (percentage < 60) {
      // 30-60%: Yellow background, black text
      return {
        'bgColor': PdfColor.fromHex("#FFEB00"),
        'textColor': PdfColors.black,
      };
    } else {
      // 60-100%: Green background, white text
      return {
        'bgColor': PdfColor.fromHex("#12B981"),
        'textColor': PdfColors.white,
      };
    }
  }

  static pw.TableRow _buildKpiRow(
    String metric,
    String value,
  ) {
    return pw.TableRow(
      children: [
        _buildTableCell(metric),
        _buildTableCell(value),
      ],
    );
  }

  static pw.TableRow _buildKpiRowColored(
    String metric,
    String value,
    PdfColor color,
  ) {
    return pw.TableRow(
      children: [
        pw.Padding(
          padding: const pw.EdgeInsets.all(8),
          child: pw.Row(
            children: [
              pw.SizedBox(width: 6),
              pw.Text(metric),
            ],
          ),
        ),
        _buildTableCell(value, textColor: color),
      ],
    );
  }

  static pw.Widget _buildStatusBadge(String status) {
    final PdfColor color = _getStatusColor(status);
    // Use black text for "completed" status, white for others
    final textColor =
        status.toLowerCase() == 'completed' ? PdfColors.black : PdfColors.white;

    return pw.Container(
      alignment: pw.Alignment.center,
      padding: const pw.EdgeInsets.all(8),
      decoration: pw.BoxDecoration(
        color: color,
      ),
      child: pw.Text(
        status,
        style: pw.TextStyle(
          color: textColor,
          fontSize: 10,
          fontWeight: pw.FontWeight.bold,
        ),
      ),
    );
  }

  static PdfColor _getStatusColor(String status) {
    switch (status.toLowerCase()) {
      // Task status colors
      case "completed":
        return PdfColor.fromHex("#C9F1FF");
      case "accepted":
        return PdfColor.fromHex("#8BDFFB");
      case "on going":
      case "ongoing":
        return PdfColor.fromHex("#33B8E4");
      case "requestforclosure":
      case "request for closure":
        return PdfColor.fromHex("#208AAC");
      case "pending":
        return PdfColor.fromHex("#19586C");
      case "rejected":
        return PdfColor.fromHex("#03171E");

      // Odor level status colors (existing)
      case "healthy":
        return PdfChartColors.good;
      case "moderate":
        return PdfChartColors.moderate;
      case "unhealthy":
        return PdfChartColors.critical;

      default:
        return PdfColors.grey;
    }
  }

  /// Get Tasks Completed from Task_status_distribution
  static String _getTasksCompleted(
      dashboard_task_model.TaskStatusDistribution? taskStatusDistribution) {
    if (taskStatusDistribution == null ||
        taskStatusDistribution.completedCount == null) {
      return "0";
    }
    return taskStatusDistribution.completedCount ?? "0";
  }

  /// Get Alerts Received count from alerts_notification array
  static String _getAlertsReceived(DashboardData? dashboardData) {
    if (dashboardData?.results?.alertsNotification == null) {
      return "0";
    }
    return "${dashboardData!.results!.alertsNotification!.length}";
  }

  /// Get max value of avg_ppm_avg from avgppm_time_range array
  static String _getMaxAvgPpmAvg(DashboardData? dashboardData) {
    if (dashboardData?.results?.avgppmTimeRange == null ||
        dashboardData!.results!.avgppmTimeRange!.isEmpty) {
      return "0";
    }

    double maxValue = 0;
    for (var item in dashboardData.results!.avgppmTimeRange!) {
      final avgPpmAvg = double.tryParse(item.avgPpmAvg ?? "0") ?? 0;
      if (avgPpmAvg > maxValue) {
        maxValue = avgPpmAvg;
      }
    }

    return maxValue.toStringAsFixed(2);
  }

  /// Get max value of avg_pcd_max from avgppm_time_range array
  static String _getMaxAvgPcdMax(DashboardData? dashboardData) {
    if (dashboardData?.results?.avgppmTimeRange == null ||
        dashboardData!.results!.avgppmTimeRange!.isEmpty) {
      return "0";
    }

    double maxValue = 0;
    for (var item in dashboardData.results!.avgppmTimeRange!) {
      final avgPcdMax = double.tryParse(item.avgPcdMax ?? "0") ?? 0;
      if (avgPcdMax > maxValue) {
        maxValue = avgPcdMax;
      }
    }

    return maxValue.toStringAsFixed(2);
  }

  /// Get AQI value from gauge_graph_data -> avg_ammonia (just the value, no arrow/percentage)
  static Map<String, dynamic> _getAvgAqiValue(DashboardData? dashboardData) {
    final gaugeData = dashboardData?.results?.gaugeGraphData;

    if (gaugeData == null || gaugeData.avgAmonia == null) {
      return {
        'value': 'N/A',
        'color': PdfChartColors.blackText,
      };
    }

    // Return just the avg_ammonia value with black color
    return {
      'value': gaugeData.avgAmonia!,
      'color': PdfChartColors.blackText,
    };
  }

  /// Get Usage value from gauge_graph_data -> pcd_max (just the value, no arrow/percentage)
  static Map<String, dynamic> _getAvgUsageValue(DashboardData? dashboardData) {
    final gaugeData = dashboardData?.results?.gaugeGraphData;

    if (gaugeData == null || gaugeData.pcdMax == null) {
      return {
        'value': 'N/A',
        'color': PdfChartColors.blackText,
      };
    }

    // Return just the pcd_max value with black color
    return {
      'value': gaugeData.pcdMax!,
      'color': PdfChartColors.blackText,
    };
  }

  /// Get formatted "Changes from Yesterday" value for alerts with arrow, count, and percentage
 /* static Map<String, dynamic> _getChangesFromYesterdayAlertTrend(
      DashboardData? dashboardData) {
    final trend = dashboardData?.results?.todayVsYesterdayAlertTrend;

    if (trend == null) {
      return {
        'value': 'N/A',
        'color': PdfChartColors.blackText,
      };
    }

    // Determine arrow direction and color
    final arrowDirection = trend.arrowDirection?.toLowerCase() ?? '';
    final isUp = arrowDirection == 'up';
    // Use ASCII characters that render reliably in PDF
    // Using caret (^) for up and lowercase v for down
    final arrow = isUp ? '^' : 'v';
    final color = isUp ? PdfChartColors.critical : PdfChartColors.good;

    // Get percentage difference (use absolute value to remove negative sign)
    String percentageText = '%';
    if (trend.percentageDifference != null) {
      if (trend.percentageDifference is num) {
        final pct = trend.percentageDifference as num;
        final absPct = pct.abs();
        percentageText = '${absPct.toStringAsFixed(1)}%';
      } else if (trend.percentageDifference is String) {
        final pctValue =
            double.tryParse(trend.percentageDifference.toString()) ?? 0.0;
        final absPct = pctValue.abs();
        percentageText = '${absPct.toStringAsFixed(1)}%';
      }
    }

    // Format: "^ 10.0%" or "v 5.0%" (no negative sign)
    final formattedValue = '$arrow  $percentageText';

    return {
      'value': formattedValue,
      'color': color,
    };
  }*/

  static Map<String, dynamic> _getChangesFromYesterdayAlertTrend(
      DashboardData? dashboardData) {
    final trend = dashboardData?.results?.todayVsYesterdayAlertTrend;

    if (trend == null) {
      return {
        'value': 'N/A',
        'color': PdfChartColors.blackText,
      };
    }

    final percentage = trend.percentageDifference;

    // Normalize to numeric value for comparison (percentageDifference can be String or num)
    double? numericValue;
    if (percentage is num) {
      numericValue = percentage.toDouble();
    } else if (percentage is String) {
      final cleaned = percentage.trim().toLowerCase();
      if (cleaned.replaceAll(' ', '') != 'nodata') {
        numericValue = double.tryParse(cleaned);
      }
    }

    final isPositive = (numericValue != null && numericValue >= 0);
    final arrow = isPositive ? '^' : 'v';
    final color = isPositive ? PdfChartColors.good : PdfChartColors.critical;

    String valueText = 'N/A';

    if (percentage != null) {
      // ✅ If it's a number (int or double)
      if (percentage is num) {
        final absPct = percentage.abs();
        valueText = '${absPct.toStringAsFixed(1)}%';
      }
      // ✅ If it's a String
      else if (percentage is String) {
        final cleaned = percentage.trim().toLowerCase();

        // Check for "no data" ignoring spaces & case
        if (cleaned.replaceAll(' ', '') == 'nodata') {
          valueText = 'No Comparison Data';
        } else {
          final parsed = double.tryParse(cleaned);
          if (parsed != null) {
            valueText = '${parsed.abs().toStringAsFixed(1)}%';
          } else {
            valueText = 'No Comparison Data';
          }
        }
      }
    }

    // If it's "No Comparison Data", don't show arrow
    if (valueText == 'No Comparison Data') {
      return {
        'value': valueText,
        'color': PdfChartColors.blackText,
      };
    }

    return {
      'value': '$arrow $valueText',
      'color': color,
    };
  }

  /// Get formatted "Changes from..." value for AQI with arrow and percentage
  /*static Map<String, dynamic> _getChangesFromAqi(DashboardData? dashboardData) {
    final comparison = dashboardData?.results?.avgppmPeriodComparison;

    if (comparison == null || comparison.ppmAvgDiffPct == null) {
      return {
        'value': 'N/A',
        'color': PdfChartColors.blackText,
      };
    }

    // Determine if the change is positive (increase) or negative (decrease)
    final pctValue = comparison.ppmAvgDiffPct is num
        ? comparison.ppmAvgDiffPct as num
        : (double.tryParse(comparison.ppmAvgDiffPct.toString()) ?? 0.0);
    final isPositive = pctValue > 0;
    final arrow = isPositive ? '^' : 'v';
    final color = isPositive ? PdfChartColors.good : PdfChartColors.critical;

    // Format percentage (use absolute value to remove negative sign)
    final absPct = pctValue.abs();
    final percentageText = '${absPct.toStringAsFixed(1)}%';

    // Format: "^ 10.0%" or "v 5.0%" (no negative sign)
    final formattedValue = '$arrow  $percentageText';

    return {
      'value': formattedValue,
      'color': color,
    };
  }*/

  static Map<String, dynamic> _getChangesFromAqi(
      DashboardData? dashboardData) {
    final comparison = dashboardData?.results?.avgppmPeriodComparison;

    if (comparison == null || comparison.ppmAvgDiffPct == null) {
      return {
        'value': 'N/A',
        'color': PdfChartColors.blackText,
      };
    }

    final rawValue = comparison.ppmAvgDiffPct;
    String valueText = 'N/A';

    if (rawValue is num) {
      final absPct = rawValue.abs();
      valueText = '${absPct.toStringAsFixed(1)}%';
    } else if (rawValue is String) {
      final cleaned = rawValue.trim().toLowerCase();

      // Check for "no data" ignoring spaces and case
      if (cleaned.replaceAll(' ', '') == 'nodata') {
        valueText = 'No Comparison Data';
      } else {
        final parsed = double.tryParse(cleaned);
        if (parsed != null) {
          valueText = '${parsed.abs().toStringAsFixed(1)}%';
        } else {
          valueText = 'No Comparison Data';
        }
      }
    }

    // If no comparison data → return without arrow
    if (valueText == 'No Comparison Data') {
      return {
        'value': valueText,
        'color': PdfChartColors.blackText,
      };
    }

    // Determine direction for numeric values
    final pctValue = rawValue is num
        ? rawValue
        : (double.tryParse(rawValue.toString()) ?? 0.0);

    final isPositive = pctValue >= 0;
    final arrow = isPositive ? '^' : 'v';
    final color =
    isPositive ? PdfChartColors.good : PdfChartColors.critical;

    return {
      'value': '$arrow  $valueText',
      'color': color,
    };
  }

  /// Get formatted "Changes from..." value for Usage with arrow and percentage
 /* static Map<String, dynamic> _getChangesFromUsage(
      DashboardData? dashboardData) {
    final comparison = dashboardData?.results?.avgppmPeriodComparison;

    if (comparison == null || comparison.pcdMaxDiffPct == null) {
      return {
        'value': 'N/A',
        'color': PdfChartColors.blackText,
      };
    }

    // Determine if the change is positive (increase) or negative (decrease)
    final pctValue = comparison.pcdMaxDiffPct is num
        ? comparison.pcdMaxDiffPct as num
        : (double.tryParse(comparison.pcdMaxDiffPct.toString()) ?? 0.0);
    final isPositive = pctValue > 0;
    final arrow = isPositive ? '^' : 'v';
    final color = isPositive ? PdfChartColors.good : PdfChartColors.critical;

    // Format percentage (use absolute value to remove negative sign)
    final absPct = pctValue.abs();
    final percentageText = '${absPct.toStringAsFixed(1)}%';

    // Format: "^ 10.0%" or "v 5.0%" (no negative sign)
    final formattedValue = '$arrow  $percentageText';

    return {
      'value': formattedValue,
      'color': color,
    };
  }*/

  static Map<String, dynamic> _getChangesFromUsage(
      DashboardData? dashboardData) {
    final comparison = dashboardData?.results?.avgppmPeriodComparison;

    if (comparison == null || comparison.pcdMaxDiffPct == null) {
      return {
        'value': 'N/A',
        'color': PdfChartColors.blackText,
      };
    }

    final rawValue = comparison.pcdMaxDiffPct;
    String valueText = 'N/A';

    if (rawValue is num) {
      final absPct = rawValue.abs();
      valueText = '${absPct.toStringAsFixed(1)}%';
    } else if (rawValue is String) {
      final cleaned = rawValue.trim().toLowerCase();

      // Check for "no data" ignoring spaces and case
      if (cleaned.replaceAll(' ', '') == 'nodata') {
        valueText = 'No Comparison Data';
      } else {
        final parsed = double.tryParse(cleaned);
        if (parsed != null) {
          valueText = '${parsed.abs().toStringAsFixed(1)}%';
        } else {
          valueText = 'No Comparison Data';
        }
      }
    }

    // If no comparison data → return without arrow
    if (valueText == 'No Comparison Data') {
      return {
        'value': valueText,
        'color': PdfChartColors.blackText,
      };
    }

    // Determine direction
    final pctValue = rawValue is num
        ? rawValue
        : (double.tryParse(rawValue.toString()) ?? 0.0);

    final isPositive = pctValue > 0;
    final arrow = isPositive ? '^' : 'v';
    final color =
    isPositive ? PdfChartColors.good : PdfChartColors.critical;

    return {
      'value': '$arrow  $valueText',
      'color': color,
    };
  }

  /// Get the "Changes from..." label based on selected range
  static String _getChangesLabel(String? selectedRange) {
    print("Selected Range: $selectedRange");
    if (selectedRange == null) {
      return "Changes from Yesterday";
    }

    switch (selectedRange) {
      case 'Today':
        return "Changes from Yesterday";
      case '7 days':
        return "Changes from last week";
      case 'Month':
        return "Changes from last month";
      default:
        return "Changes from Yesterday";
    }
  }

  /// Build odor level rows from avgppm_time_range API data
  static List<pw.TableRow> _buildOdorLevelRows(DashboardData? dashboardData) {
    if (dashboardData?.results?.avgppmTimeRange == null ||
        dashboardData!.results!.avgppmTimeRange!.isEmpty) {
      return [
        pw.TableRow(
          children: [
            _buildTableCell("No data available"),
            _buildTableCell(""),
            _buildTableCell(""),
            _buildTableCell(""),
          ],
        ),
      ];
    }

    final rangeOfPpm = dashboardData.results?.rangeOfPpm;
    final healthyMax = double.tryParse(rangeOfPpm?.healthyMax ?? "0") ?? 0;
    final moderateMax = double.tryParse(rangeOfPpm?.moderateMax ?? "0") ?? 0;

    return dashboardData.results!.avgppmTimeRange!.map((item) {
      final timeRange = _convertTo12HourFormat(item.timeRange ?? "");
      final avgPpmAvg = item.avgPpmAvg ?? "0";
      final avgPcdMax = item.avgPcdMax ?? "0";
      final ppmValue = double.tryParse(avgPpmAvg) ?? 0;

      // Determine status based on ppm value and thresholds
      String status;
      if (ppmValue <= healthyMax) {
        status = "Healthy";
      } else if (ppmValue <= moderateMax) {
        status = "Moderate";
      } else {
        status = "Unhealthy";
      }

      return pw.TableRow(
        children: [
          _buildTableCell(timeRange),
          _buildTableCell(avgPpmAvg),
          _buildTableCell(avgPcdMax),
          _buildStatusBadge(status),
        ],
      );
    }).toList();
  }

  /// Convert 24-hour time range format (e.g., "0-3", "3-6") to 12-hour format (e.g., "12 AM - 3 AM", "3 AM - 6 AM")
  static String _convertTo12HourFormat(String timeRange) {
    try {
      // Parse time range like "0-3", "3-6", "6-9", etc.
      final parts = timeRange.split("-");
      if (parts.length != 2) {
        return timeRange; // Return original if format is unexpected
      }

      final startHour = int.tryParse(parts[0]) ?? 0;
      final endHour = int.tryParse(parts[1]) ?? 0;

      String formatHour(int hour) {
        if (hour == 0) {
          return "12 AM";
        } else if (hour < 12) {
          return "$hour AM";
        } else if (hour == 12) {
          return "12 PM";
        } else {
          return "${hour - 12} PM";
        }
      }

      return "${formatHour(startHour)} - ${formatHour(endHour)}";
    } catch (e) {
      return timeRange; // Return original if parsing fails
    }
  }

  /// Build task audit rows from Task_monitoring API data
  static List<pw.TableRow> _buildTaskAuditRows(
      List<TaskMonitoring>? taskMonitoring) {
    if (taskMonitoring == null || taskMonitoring.isEmpty) {
      return [
        pw.TableRow(
          children: [
            _buildTableCell("No data available"),
            _buildTableCell(""),
            _buildTableCell(""),
          ],
        ),
      ];
    }

    return taskMonitoring.map((task) {
      final taskName = task.taskTemplateName ?? "N/A";
      final janitorName = task.janitorName ?? "Unassigned";
      final status = task.status ?? "N/A";

      return pw.TableRow(
        children: [
          _buildTableCell(taskName),
          _buildTableCell(janitorName),
          _buildStatusBadge(status),
        ],
      );
    }).toList();
  }

  /// Build critical alerts rows from alerts_notification API data
  static List<pw.TableRow> _buildCriticalAlertsRows(
      DashboardData? dashboardData) {
    if (dashboardData?.results?.alertsNotification == null ||
        dashboardData!.results!.alertsNotification!.isEmpty) {
      return [
        pw.TableRow(
          decoration: pw.BoxDecoration(
            color: PdfChartColors.criticalLight,
          ),
          children: [
            _buildTableCell("No alerts available"),
            _buildTableCell(""),
          ],
        ),
      ];
    }

    return dashboardData.results!.alertsNotification!.map((alert) {
      final message = alert.message ?? "N/A";
      final time = _formatDateTimeTo12Hour(alert.ppmTime);

      return pw.TableRow(
        decoration: pw.BoxDecoration(
          color: PdfChartColors.criticalLight,
        ),
        children: [
          _buildTableCell(message),
          _buildTableCell(time),
        ],
      );
    }).toList();
  }

  /// Format DateTime to 12-hour format (e.g., "2:30 PM", "11:45 AM")
  static String _formatDateTimeTo12Hour(DateTime? dateTime) {
    if (dateTime == null) {
      return "N/A";
    }

    final hour = dateTime.hour;
    final minute = dateTime.minute;
    final period = hour >= 12 ? "PM" : "AM";
    final hour12 = hour == 0
        ? 12
        : hour > 12
            ? hour - 12
            : hour;
    final minuteStr = minute.toString().padLeft(2, '0');

    return "$hour12:$minuteStr $period";
  }

  /// Build janitor performance rows from Task_monitoring API data
  static List<pw.TableRow> _buildJanitorPerformanceRows(
      List<TaskMonitoring>? taskMonitoring) {
    if (taskMonitoring == null || taskMonitoring.isEmpty) {
      return [
        pw.TableRow(
          children: [
            _buildTableCell("No data available"),
            _buildTableCell(""),
            _buildTableCell(""),
          ],
        ),
      ];
    }

    // Group tasks by janitor name and calculate statistics
    final janitorStats = <String, Map<String, int>>{};

    for (var task in taskMonitoring) {
      if (task.janitorName != null && task.janitorName!.isNotEmpty) {
        final janitorName = task.janitorName!;

        // Initialize if not exists
        if (!janitorStats.containsKey(janitorName)) {
          janitorStats[janitorName] = {
            'assigned': 0,
            'completed': 0,
          };
        }

        // Count each TaskMonitoring entry as 1 assigned task (not based on taskNames.length)
        janitorStats[janitorName]!['assigned'] =
            (janitorStats[janitorName]!['assigned'] ?? 0) + 1;

        // Count as completed if status is "completed" (case-insensitive)
        // Each TaskMonitoring entry with completed status = 1 completed task
        if (task.status != null && task.status!.toLowerCase() == 'completed') {
          janitorStats[janitorName]!['completed'] =
              (janitorStats[janitorName]!['completed'] ?? 0) + 1;
        }
      }
    }

    if (janitorStats.isEmpty) {
      return [
        pw.TableRow(
          children: [
            _buildTableCell("No janitors available"),
            _buildTableCell(""),
            _buildTableCell(""),
          ],
        ),
      ];
    }

    // Convert to sorted list for consistent ordering
    final sortedJanitorNames = janitorStats.keys.toList()..sort();

    return sortedJanitorNames.map((janitorName) {
      final stats = janitorStats[janitorName]!;
      final assigned = stats['assigned'] ?? 0;
      final completed = stats['completed'] ?? 0;

      // Format: "completed/assigned"
      final tasksCompletedText = '$completed/$assigned';

      // Calculate completion rate percentage
      final completionRateValue =
          assigned > 0 ? (completed / assigned) * 100 : 0.0;
      final completionRate = completionRateValue.toStringAsFixed(1);
      final completionRateText = '$completionRate%';

      // Get color based on completion rate percentage
      final completionRateColor = _getCompletionRateColor(completionRateValue);

      return pw.TableRow(
        children: [
          _buildTableCell(janitorName),
          _buildTableCell(tasksCompletedText),
          _buildTableCellWithBackground(
            completionRateText,
            backgroundColor: completionRateColor['bgColor'] as PdfColor,
            textColor: completionRateColor['textColor'] as PdfColor,
          ),
        ],
      );
    }).toList();
  }
}

class PdfChartColors {
  static final PdfColor airQuality = PdfColor.fromHex("#8BDFFB");

  static PdfColor usage = PdfColor.fromHex("#FFEB00");

  static PdfColor threshold = PdfColor.fromHex("#FF0014");

  static PdfColor good = PdfColor.fromHex("#00C853");

  static PdfColor moderate = PdfColor.fromHex("#FFA000");

  static PdfColor critical = PdfColor.fromHex("#D50000");

  static PdfColor headerBackground = PdfColor.fromHex("#E3F2FD");

  static PdfColor criticalLight = PdfColor.fromHex("#FFD6D6");

  static PdfColor blackText = PdfColors.black;
}

extension PdfColorOpacityExtension on PdfColor {
  PdfColor withOpacity(double opacity) {
    return PdfColor(red, green, blue, opacity);
  }
}
