import 'package:flutter/material.dart';

Map<String, Color> colorMap = {
  'black': Colors.black,
  'blue': Colors.blue,
  'green': Colors.green,
  'red': Colors.red,
  'yellow': Colors.yellow,
  'white': Colors.white,
  'grey': Colors.grey,
  'teal': Colors.teal,
  'amber': Colors.amber,
  'cyan': Colors.cyan,
  'deeporange': Colors.deepOrange,
  'deeppurple': Colors.deepPurple,
  'indigo': Colors.indigo,
  'lightblue': Colors.lightBlue,
  'lightgreen': Colors.lightGreen,
  'lime': Colors.lime,
  'orange': Colors.orange,
  'pink': Colors.pink,
  'purple': Colors.purple,
  'brown': Colors.brown,
  'bluegrey': Colors.blueGrey,
  'aliceblue': const Color(0xFFF0F8FF),
  'antiquewhite': const Color(0xFFFAEBD7),
  'aqua': const Color(0xFF00FFFF),
  'aquamarine': const Color(0xFF7FFFD4),
  'azure': const Color(0xFFF0FFFF),
  'beige': const Color(0xFFF5F5DC),
  'bisque': const Color(0xFFFFE4C4),
  'blanchedalmond': const Color(0xFFFFEBCD),
  'blueviolet': const Color(0xFF8A2BE2),
  'burlywood': const Color(0xFFDEB887),
  'cadetblue': const Color(0xFF5F9EA0),
  'chartreuse': const Color(0xFF7FFF00),
  'chocolate': const Color(0xFFD2691E),
  'coral': const Color(0xFFFF7F50),
  'cornflowerblue': const Color(0xFF6495ED),
  'cornsilk': const Color(0xFFFFF8DC),
  'crimson': const Color(0xFFDC143C),
  'darkblue': const Color(0xFF00008B),
  'darkcyan': const Color(0xFF008B8B),
  'darkgoldenrod': const Color(0xFFB8860B),
  'darkgray': const Color(0xFFA9A9A9),
  'darkgreen': const Color(0xFF006400),
  'darkkhaki': const Color(0xFFBDB76B),
  'magenta': const Color(0xFF8B008B),
  'darkmagenta': const Color(0xFF8B008B),
  'darkolivegreen': const Color(0xFF556B2F),
  'darkorange': const Color(0xFFFF8C00),
  'darkorchid': const Color(0xFF9932CC),
  'darkred': const Color(0xFF8B0000),
  'darksalmon': const Color(0xFFE9967A),
  'darkseagreen': const Color(0xFF8FBC8F),
  'darkslateblue': const Color(0xFF483D8B),
  'darkslategray': const Color(0xFF2F4F4F),
  'darkturquoise': const Color(0xFF00CED1),
  'darkviolet': const Color(0xFF9400D3),
  'deeppink': const Color(0xFFFF1493),
  'deepskyblue': const Color(0xFF00BFFF),
  'dimgray': const Color(0xFF696969),
  'dodgerblue': const Color(0xFF1E90FF),
  'firebrick': const Color(0xFFB22222),
  'floralwhite': const Color(0xFFFFFAF0),
  'forestgreen': const Color(0xFF228B22),
  'fuchsia': const Color(0xFFFF00FF),
  'gainsboro': const Color(0xFFDCDCDC),
  'ghostwhite': const Color(0xFFF8F8FF),
  'gold': const Color(0xFFFFD700),
  'goldenrod': const Color(0xFFDAA520),
  'greenyellow': const Color(0xFFADFF2F),
  'honeydew': const Color(0xFFF0FFF0),
  'hotpink': const Color(0xFFFF69B4),
  'indianred': const Color(0xFFCD5C5C),
  'ivory': const Color(0xFFFFFFF0),
  'khaki': const Color(0xFFF0E68C),
  'lavender': const Color(0xFFE6E6FA),
  'lavenderblush': const Color(0xFFFFF0F5),
  'lawngreen': const Color(0xFF7CFC00),
  'lemonchiffon': const Color(0xFFFFFACD),
  'lightcoral': const Color(0xFFF08080),
  'lightcyan': const Color(0xFFE0FFFF),
  'lightgoldenrodyellow': const Color(0xFFFAFAD2),
  'lightgray': const Color(0xFFD3D3D3),
  'lightpink': const Color(0xFFFFB6C1),
  'lightsalmon': const Color(0xFFFFA07A),
  'lightseagreen': const Color(0xFF20B2AA),
  'lightskyblue': const Color(0xFF87CEFA),
  'lightslategray': const Color(0xFF778899),
  'lightsteelblue': const Color(0xFFB0C4DE),
  'lightyellow': const Color(0xFFFFFFE0),
  'limegreen': const Color(0xFF32CD32),
  'linen': const Color(0xFFFAF0E6),
  'maroon': const Color(0xFF800000),
  'mediumaquamarine': const Color(0xFF66CDAA),
  'mediumblue': const Color(0xFF0000CD),
  'mediumorchid': const Color(0xFFBA55D3),
  'mediumpurple': const Color(0xFF9370DB),
  'mediumseagreen': const Color(0xFF3CB371),
  'mediumslateblue': const Color(0xFF7B68EE),
  'mediumspringgreen': const Color(0xFF00FA9A),
  'mediumturquoise': const Color(0xFF48D1CC),
  'mediumvioletred': const Color(0xFFC71585),
  'midnightblue': const Color(0xFF191970),
  'mintcream': const Color(0xFFF5FFFA),
  'mistyrose': const Color(0xFFFFE4E1),
  'moccasin': const Color(0xFFFFE4B5),
  'navajowhite': const Color(0xFFFFDEAD),
  'navy': const Color(0xFF000080),
  'oldlace': const Color(0xFFFDF5E6),
  'olive': const Color(0xFF808000),
  'olivedrab': const Color(0xFF6B8E23),
  'orangered': const Color(0xFFFF4500),
  'orchid': const Color(0xFFDA70D6),
  'palegoldenrod': const Color(0xFFEEE8AA),
  'palegreen': const Color(0xFF98FB98),
  'paleturquoise': const Color(0xFFAFEEEE),
  'palevioletred': const Color(0xFFDB7093),
  'papayawhip': const Color(0xFFFFEFD5),
  'peachpuff': const Color(0xFFFFDAB9),
  'peru': const Color(0xFFCD853F),
  'plum': const Color(0xFFDDA0DD),
  'powderblue': const Color(0xFFB0E0E6),
};

Color getColorFromString(String colorName) {
  return colorMap[colorName.toLowerCase()] ?? Colors.transparent;
}
