name: Flutter CI/CD

on:
  push:
    branches:
      - nov_dev

jobs:
  flutter:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Check out code
        uses: actions/checkout@v3

      # Step 2: Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:    
          channel: stable

      # Step 3: Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # Step 4: Analyze Code
      - name: Analyze Code
        run: flutter analyze

      # Step 5: Run Unit Tests
      - name: Run Unit Tests
        run: |
          mkdir -p flutter-test-results
          flutter test > flutter-test-results/results.txt
        continue-on-error: true

      # Step 6: Collect and Upload Test Results
      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: flutter-test-results
          path: flutter-test-results/results.txt

      # Step 7: Upload coverage report
      - name: Upload coverage report
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage/lcov.info
