name: Flutter Android Debug APK

on:
  push:
    branches:
      - test

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - uses: actions/checkout@v5

      # Setup Java 17
      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '17'

      # Setup Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.38.5'

      # Check Flutter version
      - name: Flutter Version
        run: flutter --version

      # Install dependencies
      - name: Install Dependencies
        run: flutter pub get

      # Build Debug APK
      - name: Build Debug APK
        run: flutter build apk --debug

      # Copy APK to root
      - name: Copy APK
        run: |
          find build/app/outputs/flutter-apk -name "*.apk" -exec cp {} flutter-debug.apk \;

      # Upload APK
      - name: Upload APK
        uses: actions/upload-artifact@v5
        with:
          name: flutter-debug-apk
          path: flutter-debug.apk
