name: Flutter CI/CD

on:
  push:
    branches:
      - master

jobs:
  flutter:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Check out code
        uses: actions/checkout@v3

      # Step 2: Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:    
          channel: stable

      # Step 3: Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # Step 4: Analyze code
      - name: Analyze code
        run: flutter analyze --verbose

      # Step 5: Run all tests and generate coverage report
      - name: Run all tests and generate coverage
        run: flutter test --coverage
        continue-on-error: true
        
      # Step 6: Upload test result artifacts (JUnit-style)
      - name: Upload test result artifacts
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: result.json

      # Step 7: Upload coverage report
      - name: Upload coverage report
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage/lcov.info
